export {
  createDatabaseClient,
  databaseUrl,
  LOCAL_DATABASE_URL,
  type DatabaseClient,
} from './client';
export * as schema from './schema/index';
export {
  ensureIdentityForAuthUser,
  completeAccountSetup,
  setLastActiveWorkspace,
  recordAuthAuditEvent,
  type CompleteAccountSetupInput,
  type EnsureIdentityInput,
  type IdentityResolutionRecord,
  type IdentityRoleAssignmentRecord,
} from './repositories/identity';
export {
  listSubjects,
  ensureFamilyAccountForGuardian,
  createDependentStudent,
  ensureIndependentStudentProfile,
  listAccessibleStudents,
  listSubjectSections,
  createSubjectSection,
  subjectSectionBelongsToUser,
  type StudentRecord,
  type SubjectSectionRecord,
  type SubjectOption,
} from './repositories/students';
export {
  searchPublicTutors,
  findPublicTutorByReference,
  listShortlist,
  addToShortlist,
  removeFromShortlist,
  type PublicTutorRow,
  type TutorSearchQuery,
  type ShortlistEntryRow,
  type ShortlistAddOutcome,
} from './repositories/discovery';
export {
  createIntendedLessonRequest,
  withdrawRequest,
  expireOverdueRequests,
  currentRequestRules,
  subjectSectionOwner,
  acceptTutorRequestTime,
  declineTutorRequest,
  NoTutorAvailableError,
  RequestNotOpenError,
  selectAcceptedTutorRequest,
  SelectionNoLongerAvailableError,
  SlotUnavailableError,
  TimeNoLongerAvailableError,
  type SelectAcceptedRequestInput,
  type SelectionOutcome,
  type AcceptedTutorRequest,
  type AcceptTutorRequestInput,
  type DeclineTutorRequestInput,
  RequestValidationError,
  type CreateIntendedLessonRequestInput,
  type SubjectSectionDraft,
  type CreatedIntendedLessonRequest,
  type WithdrawInput,
  type ExpireRequestsResult,
} from './repositories/lesson-requests';
export {
  listRequestsForStudents,
  findRequestForStudents,
  listRequestsForTutor,
  findRequestForTutor,
  tutorProfileForUser,
  type FamilyRequestView,
  type FamilyTutorRequestView,
  type TutorRequestView,
} from './repositories/request-projections';
export {
  loadRequestRules,
  setRuleSetting,
  type LoadedRequestRules,
} from './repositories/rule-settings';
export {
  archiveAvailabilityException,
  archiveAvailabilityRule,
  bookableSlotsForSubjectSection,
  bookableSlotsForTutors,
  tutorMinimumGapMinutes,
  setTutorMinimumGapMinutes,
  createAvailabilityException,
  createAvailabilityRule,
  listAvailabilityExceptions,
  listAvailabilityRules,
  listTutorReservations,
  updateAvailabilityException,
  updateAvailabilityRule,
  type AvailabilityExceptionRecord,
  type AvailabilityRuleRecord,
  type BookableSlot,
  type BookableSlotsQuery,
  type CreateAvailabilityExceptionInput,
  type CreateAvailabilityRuleInput,
  type SubjectSectionSlotsQuery,
  type TutorBookableSlots,
  type TutorReservationRecord,
  type UpdateAvailabilityExceptionChanges,
  type UpdateAvailabilityRuleChanges,
} from './repositories/availability';

export {
  listBookableServices,
  formatsForVersion,
  type BookableServiceVersion,
  type BookableTutorServices,
} from './repositories/services';
